// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_message.proto

package com.github.jianlu8023.grpcexample.proto.message;

public final class BaseMessage {
  private BaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022base_message.proto\"E\n\016MessageRequest\022\014" +
      "\n\004type\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\014\n\004from\030\003 \001(\t\022" +
      "\n\n\002to\030\004 \001(\t\"F\n\017MessageResponse\022\014\n\004type\030\001" +
      " \001(\t\022\013\n\003msg\030\002 \001(\t\022\014\n\004from\030\003 \001(\t\022\n\n\002to\030\004 " +
      "\001(\t2@\n\016MessageService\022.\n\007message\022\017.Messa" +
      "geRequest\032\020.MessageResponse\"\000B@\n/com.git" +
      "hub.jianlu8023.grpcexample.proto.message" +
      "B\013BaseMessageP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "Type", "Msg", "From", "To", });
    internal_static_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageResponse_descriptor,
        new java.lang.String[] { "Type", "Msg", "From", "To", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
