// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_message.proto

package com.github.jianlu8023.grpcexample.proto.message;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string from = 3;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 3;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 4;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 4;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();
}
