// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.github.jianlu8023.grpcexample.proto.demo;

public interface DemoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
