// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.github.jianlu8023.grpcexample.proto.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
