// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package com.github.jianlu8023.grpcexample.proto.ping;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Ping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string ipaddr = 3;</code>
   */
  java.lang.String getIpaddr();
  /**
   * <code>string ipaddr = 3;</code>
   */
  com.google.protobuf.ByteString
      getIpaddrBytes();
}
